# fly.toml app configuration file generated for example-late-snow-8708 on 2025-05-23T14:19:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'example-late-snow-8708'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
